services:
  postgres:
    image: postgres:15-alpine
    container_name: stock-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stock-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - postgres
    networks:
      - stock-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - stock-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  stock-network:
    driver: bridge
